### ISSUE TITLE
Does the script work? 

### ISSUE THREAD

**Issue by Bjodol** [mcgrews3/bb8-driver#1]
Hi! We are looking into creating som custome instruction scripts for the bb-8 bot for an upcomming event in one week... Have you been able to contact the bb-8 and send instructions to it?

**Comment by mcgrews3** [comment]
Some of the scripts work - you will also need to create a data.json and put your BB8's GUID in it.  You can get the GUID by using a tool like cylon-ble...

```
{
    "devices": {
        "bb8":"YOUR_BB8_GUID"
    }
}
```

**Comment by mcgrews3** [comment]
https://github.com/hybridgroup/cylon-ble  - use **cylon-ble-scan**
